### ISSUE TITLE
Could you support exclude a whole directory in [UnloadDll]?

### ISSUE THREAD

**Issue by kraml** [snowie2000/mactype#192]
Currently Mactype may cause slow down or other problem to msys2 programs. For example this one:

https://github.com/Alexpux/MSYS2-packages/issues/393

and this one:

https://sourceforge.net/p/msys2/tickets/245/

The solution is to add some programs to the [UnloadDll] section to make mactype ignore them. However, there are hundreds of such programs in a msys2 installation, it is better to support add an folder entry in [UnloadDll] and ignore all files under it.

**Comment by snowie2000** [comment]
Can you show me some simple step to reproduce this problem?

**Comment by kraml** [comment]
You will have to install msys2 first. Here is the link: http://msys2.github.io/

I'm using the x86_64 installer. Just follow the instructions on the web page to install.

After done, open the msys2 terminal, run "pacman -Syu" to upgrade. You may notice, as mentioned in msys2 issue #393, "GPGME error: Invalid crypto engine" error message. If not, let the update finish and run pacman -Syu again and the issue should occur.

Then add gpg.exe and pacman.exe to UnloadDll, the issue should disappear.

**Comment by snowie2000** [comment]
I saw the problem. Thank you.

**Comment by kraml** [comment]
That may only be part of the problem. I also noticed that having Mactype enabled for those msys2 command line tools considerably slowed down their speed. Msys2/cygwin program are know to startup slower (on windows) then their Linux conterparts. Having Mactype hook into them make them even slower. A simple bash script may take 2~3 seconds to run, while after excluded bash in Mactype the same script may take only 1s. When running complex scripts such as the very common configure script from many source packages, the slow down could be minutes, as the configure script may call other command line programs thousands of times.

I totally understand the slow down as a trade off for better font rendering, just trying to make exclude such programs easier.

**Comment by snowie2000** [comment]
A simple investigation shows that the bash.exe brought with msys2 is hooking the some API - CreateProcessInternalW with MacType which finally leads to the GPG problem. Further code analysis will be done later. A simple workaround would be set HookChildProcesses to 0, (which will delay the render for a significant amount of time in all loading modes except registry).

**Comment by kraml** [comment]
So in registry loading mode, would child processes still get hooked even HookChildProcesses=0? I need the behavior of hook child process automatically so all my apps are rendered.

**Comment by snowie2000** [comment]
Yes, it will get hooked automatically, and it will be done by Windows AppInit_Dlls mechanism instead of MacType assembler.

**Comment by kraml** [comment]
Thank you! I will try this.

**Comment by snowie2000** [comment]
However, this mechanism will be disabled when UEFI secure boot is ON.

**Comment by snowie2000** [comment]
Try files in http://mactype.net/station/MacType_CTP_160927_2.rar
Problem has been fixed on my system.

**Comment by kraml** [comment]
With 160927_2 dlls I still see slow down of Msys2 programs if HookChildProcesses=1. No slow down if Hook=0.

This is the same as 20160904 release.

**Comment by snowie2000** [comment]
Do you still see GPGME error in this version when HookChildProcesses=1?

**Comment by kraml** [comment]
No, not any more.

**Comment by snowie2000** [comment]
Try this one: http://mactype.net/station/MacType_CTP_slow_down_fix.rar
If this patch can't fix your slow down issue, you have to give me an example script to test.

**Comment by kraml** [comment]
Slow down is still there.

Here is how to test. Cut and paste below lines into a new text file named test.sh, save it with UNIX EOL. This script simply runs "ls" (list file) command for 100 times.
-------cut starts here--------
#!/bin/bash

for i in {1..100}; do
	ls / > /dev/null 2>&1
done
-------cut ends here--------

Run it in Msys2 terminal:
$ time ./test.sh

WIth Hook=0, it takes ~ 0.2-0.4s to run this script, with Hook=1, it takes ~2s to run. FYI in the Linux VM running on the same system, this script takes only 0.1s.

Change 100 to a larger value if it doesn't give you noticeable difference between Hook=0/1 on your system.

**Comment by kraml** [comment]
BTW, above test dlls cause slower rendering. I can see flickering while my Emacs windows scrolling. I hope it is due to the non-release build, not some real slow down in the new unreleased code.

**Comment by snowie2000** [comment]
I didn't change anything in rendering part except some bug fixes. If the developer version lags, it will lag in the final release.

BTW, I find the point that slows your script down, and it takes quite a bit time to optimize. And for registry mode, it just does not load mactype to your ls.exe and bash.exe at all for some unknown reasons, that's why you didn't feel laggy.

**Comment by kraml** [comment]
For lag issue, I've tested again and confirmed that the test dlls are slower. As long as I put them in place, my Emacs start to flick while scrolling. If that is the case for next release I'm going to feel very sorry.

For script slow down, since ls.exe/bash.exe/etc. including Win console programs are all GUI-less, can MacType detect process type (console/GUI) and disable itself on console programs? After all console programs don't render any font at all, they just spit chars on stdout. Only terminal emulators need to be rendered, such as mintty.exe in Msys2 and the popular ConEmu.exe Windows cmd.exe wrapper.

**Comment by snowie2000** [comment]
I've compared all source code between the two versions, the only major difference related to rendering is the upgrade of FreeType. version 904 is compiled with freetype 2.6.5 while all the developer versions are compiled with freetype 2.7. If that's the case, I have no idea how to improve the rendering performance.

**Comment by kraml** [comment]
While I saw rendering change in freetype 2.7 mentioned in other issues, I didn't see any noticeable visual change of the rendered  fonts in the dev dlls. The only thing I saw was speed. It could be the difference is too subtle and I only focused on script speed last time. Is it really necessary to switch to 2.7 if it doesn't bring practically useful rendering advantage while in the mean time slows down? Or could you please release two separated installers in later releases with both 2.6 and 2.7 supported, until the performance problem is solved?

**Comment by snowie2000** [comment]
The most key new feature brought by FreeType 2.7 is ClearType style subpixel hinting support, which only can be seen when you set HintingMode to 0 and AA mode to 3 or 4. With this combination, you will see a clearly better font sharp then 2.6

**Comment by kraml** [comment]
I can see the difference now after change HintingMode to 0. However I personally don't like the shape rendered in such way, nor do I feel it is sharper. Anyway this is subjective opinion. I'm OK with FT 2.7 from rendering perspective since it still can provide same visual shape as 2.6 does by setting HintingMode to non-0. But the performance degradation is a challenge for me and probably many other people.

**Comment by snowie2000** [comment]
I uploaded a new version compiled with freetype 2.6.5. Have a try of it and see if the performance is any better in emacs.
Also, I optimized the Profile parser alot, so that your bash script is now much faster than previous version. (but still way slower than without mactype). The old version is about 10times slower, and the new version is about 2-3times slower. This is the best I can do now I'm afraid.

**Comment by kraml** [comment]
This one indeed improved script performance, like you mentioned, to about 2-3x slower.

However strangely it still causes slower rendering in Emacs exactly like previous dev dlls.

**Comment by snowie2000** [comment]
try this file: http://www.mactype.net/station/MacType_CTP.rar
It is released at Sep. 18. Which means its source code is close to the release version.

**Comment by kraml** [comment]
This one is OK, no flickering in Emacs.

**Comment by snowie2000** [comment]
http://mactype.net/station/MacType_CTP_160928.rar
This build will definitely fix the flickering issue in Emacs.
Actually, this issue is nothing about performance, it's an incompatibility of my clipboxfix feature, and I set clipboxfix to 0 by default again now.

**Comment by kraml** [comment]
Yes, this version doesn't cause flickring in Emacs. It makes scripts runs faster than before with Hook=1. It has the FT 2.7 shape rendering when HintingMode=0.

**Comment by snowie2000** [comment]
Yes, this build contains all the fixes and optimizations I done these days.
For script performance (i.e. process creation performance), I will not improve it in the near future. After all, it needs to load mactype and init font engine and etc. To improve it to the next stage, I need to move almost all the heavy init code to the delay code section, which is not a easy job and may cost great amount of time. 

BTW, it is easy to distinct a NE exe(console executable) from a PE exe(GUI executable), but there are many NE files that output text or invoke GUI APIs and there are also many PEs that runs in console (for example, ls.exe bash.exe pacman.exe, they are all PEs), which makes it impossible to automatically skip certain executables.

**Comment by kraml** [comment]
Thank you for the improvement and explanations, see you in other issues : D

**Comment by w1ndy** [comment]
Hi, the link above has expired, could you please update the link to a newer version? I'm also experiencing noticeable slowdown in Cygwin while scrolling text in mintty. Thanks!

**Comment by snowie2000** [comment]
Please find all CTP builds in http://mactype.net/station

**Comment by w1ndy** [comment]
@snowie2000 Got it, thanks.

**Comment by sdycjsj** [comment]
I tried MacType_CTP_160928.rar, but still saw flickering in emacs. 
I simply extract the archive to mactype installation folder. Did I miss anything?

**Comment by snowie2000** [comment]
Try disable clipboxfix by setting clipboxfix=0 in experimental section if you enabled it before.

**Comment by sdycjsj** [comment]
When I tested CTP 0928, I put the following 

[experimental@emacs.exe]
clipboxfix=0

at the end of the profile I chose. 
I still saw flickering in emacs.

PS: I was using the tray loading mode when I did the test.

**Comment by snowie2000** [comment]
The latest CTP version is 161116

**Comment by sdycjsj** [comment]
Just tried 161116, got the same problem.

**Comment by snowie2000** [comment]
flickering and slow down is totally a different thing. emacs is slow while scrolling whether you enable mactype or not.

**Comment by sdycjsj** [comment]
Well, what I can see is that compared with the case without mactype, the scrolling in emacs becomes visually quite different when mactype is enabled.

When scrolling slowly, I do see flickering.

When jumping within the buffer I see a "refresh" of the whole page, line by line. This process is not as fast as when mactype is disabled, so you can tell by naked eye. Maybe this is what you called "slow down".

Anyway, it might be a problem on my side. Thank you.

**Comment by snowie2000** [comment]
The problem you faced is totally different from what we discussed in this thread. The problem related to clipboxfix is generally a defect of emacs that it cannot properly deal with enlarged clipbox. While in your case, I don't sure it really is, but definitely not the same thing. In this case, the CTP version won't work for you.

**Comment by sdycjsj** [comment]
I see. Thank you for the clarification.

**Comment by vipexv** [comment]
I'm confused, how can you actually exclude a whole directory?

**Comment by snowie2000** [comment]
> I'm confused, how can you actually exclude a whole directory?

Like this: `c:\windows\`
Ends with a back slash.

**Comment by vipexv** [comment]
Where exactly though, in `UnloadDLL`?

Sorry for all of the questions, i would try it right now but i uninstalled and i'll try it again later.

The biggest issue for me is Gaming, i'm afraid it will get me banned from Online games, anything i should know beforehand?

**Comment by snowie2000** [comment]
Yes, add to the UnloadDll section.

DO NOT add to the exclude section! The `exclude` section only disables rendering but the DLLs will still be loaded and can potentially lead to a false positive cheat check.

Start your game but do not play, launch the macwiz to check if the game processes are marked as `ignored (disabled)`. Do not use registry mode or compatible mode as them can not be bypassed.
