### ISSUE TITLE
Render problem in JetBrain IDEs (eg. WebStorm)

### ISSUE THREAD

**Issue by AnClark** [snowie2000/mactype#355]
After installing the latest version (2017/6/28) of MacType, the font in JetBrains IDEs renders abnormal.
But the previous version of MacType is OK (2016/9/2).

## Situation
The top of every character was cut (especially Courier New).

![-1](https://user-images.githubusercontent.com/12870704/29394836-a953eaf8-833f-11e7-900b-59d264e0eb7e.png)

## My WebStorm IDE
Build #WS-172.3544.34, built on July 31, 2017
JRE: 1.8.0_152-release-915-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0.14393

**Comment by iGoo** [comment]
Me too
![qq 20170821112318](https://user-images.githubusercontent.com/5689279/29502521-455e7fd2-8663-11e7-997e-69b734b285d8.png)

**Comment by Mahayu** [comment]
#281 
That may help you.

**Comment by snowie2000** [comment]
https://github.com/snowie2000/mactype/issues/313#issuecomment-312309772

Written in Chinese, but not hard to understand the code.

**Comment by AnClark** [comment]
But my advice is to support JetBrains IDE with a patch distributed together with the latest release of MacType.

**Comment by AnClark** [comment]
Yeah, waiting for a better release. Cheers!

**Comment by Nek80** [comment]
thanks snowie!

**Comment by sammilucia** [comment]
@AnClark @lePig @Nek80 I believe this issue is fixed wit the latest build, can you please let me know if it's working for you now?

**Comment by sammilucia** [comment]
@snowie2000 is away for a few days ... just rename any files you replace so you can put them back if you need. This will tell us where the problem is either way for when he gets back 😊

**Comment by AnClark** [comment]
The problem still exists in other apps based on Java. (e.g. Logisim)
![2018-10-05_161905](https://user-images.githubusercontent.com/12870704/46524203-9a1f1280-c8ba-11e8-981c-e95e6efc132a.jpg)

**Comment by AnClark** [comment]
OK! I will have a try.

**Comment by AnClark** [comment]
The former release is installed with Windows Installer, but your latest release is using NSIS instead. It may occur some compatibility issues.

**Comment by snowie2000** [comment]
This new installer will uninstall all the previous ones so there should be no problems  in theory.

**Comment by sammilucia** [comment]
Hi @AnClark ... yes it's not NSIS it's Inno Setup. It will uninstall the old installer and do its own cleanup. There's nothing to worry about - I've thought of everything!! 😊 Just run it and let it do it's magic

In the extremely rare case where I haven't thought of everything, just let me know and I'll fix it 😊
